#!/bin/sh
echo "Download once per hour"

while true; do
	echo "Downloading!"
	wget "https://www.yr.no/sted/Sverige/V%C3%A4stra_G%C3%B6taland/G%C3%B6teborg/varsel.pdf" -O vader.pdf
	convert -verbose -density 150 -trim vader.pdf -quality 100 -flatten -sharpen 0x1.0 vader.png
	mv vader.png  vader/
	$(./dagens/html_to_file)
	mv menu.txt ./dagens/
	echo "Finished!"
	sleep 3540
done
