#!/bin/bash
#Overwrites menu.txt and starts scraper.py, writing the output to menu.txt
touch menu.txt
DIR="$( readlink -f "$( dirname "${BASH_SOURCE[0]}" )")"

python3 $DIR/scraper.py > menu.txt 2>&1
